package juegonavideno.gui;

import juegonavideno.logica.Controlador;

public class Pantalla extends javax.swing.JFrame {
    String emoji = "";
    
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_input = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_arbol = new javax.swing.JButton();
        btn_estrella = new javax.swing.JButton();
        btn_papanoel = new javax.swing.JButton();
        btn_regalo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_matriz = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_elegido = new javax.swing.JTextField();
        tf_cantidad = new javax.swing.JTextField();
        tf_encontrados = new javax.swing.JTextField();
        tf_resultado = new javax.swing.JTextField();
        btn_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Desafío Navideño");

        jLabel2.setText("Digite la cantidad de veces que cree que aparece su personaje (0 a 16):");

        tf_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("Elija su personaje:");

        btn_arbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegonavideno/imagenes/arbolnavidad64x64.png"))); // NOI18N
        btn_arbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_arbolActionPerformed(evt);
            }
        });

        btn_estrella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegonavideno/imagenes/estrella64x64.png"))); // NOI18N
        btn_estrella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estrellaActionPerformed(evt);
            }
        });

        btn_papanoel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegonavideno/imagenes/papanoel64x64.png"))); // NOI18N
        btn_papanoel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_papanoelActionPerformed(evt);
            }
        });

        btn_regalo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegonavideno/imagenes/regalonavidad64x64.png"))); // NOI18N
        btn_regalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regaloActionPerformed(evt);
            }
        });

        ta_matriz.setEditable(false);
        ta_matriz.setColumns(20);
        ta_matriz.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        ta_matriz.setRows(5);
        ta_matriz.setMargin(new java.awt.Insets(10, 6, 2, 6));
        jScrollPane1.setViewportView(ta_matriz);

        jLabel4.setText("Elegido:");

        jLabel5.setText("Cantidad:");

        jLabel6.setText("Encontrados:");

        jLabel7.setText("Resultado:");

        tf_elegido.setEditable(false);

        tf_cantidad.setEditable(false);

        tf_encontrados.setEditable(false);

        tf_resultado.setEditable(false);

        btn_reset.setBackground(new java.awt.Color(0, 153, 51));
        btn_reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegonavideno/imagenes/reset32x32.png"))); // NOI18N
        btn_reset.setText("   Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_elegido)
                    .addComponent(tf_cantidad)
                    .addComponent(tf_encontrados)
                    .addComponent(tf_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(btn_reset))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(tf_input, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_papanoel)
                                .addGap(47, 47, 47)
                                .addComponent(btn_arbol, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btn_estrella, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(btn_regalo)
                                .addGap(7, 7, 7))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(115, 115, 115))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_papanoel)
                    .addComponent(btn_estrella)
                    .addComponent(btn_regalo)
                    .addComponent(btn_arbol))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_elegido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf_encontrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_reset)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        tf_input.setText("");
        tf_elegido.setText("");
        tf_cantidad.setText("");
        tf_encontrados.setText("");
        tf_resultado.setText("");
        ta_matriz.setText("");
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_papanoelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_papanoelActionPerformed
        emoji = "🎅🏻";
        desarrolloJuego(emoji);
    }//GEN-LAST:event_btn_papanoelActionPerformed

    private void btn_arbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_arbolActionPerformed
        emoji = "🎄";
        desarrolloJuego(emoji);
    }//GEN-LAST:event_btn_arbolActionPerformed

    private void btn_estrellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estrellaActionPerformed
        emoji = "⭐";
        desarrolloJuego(emoji);
    }//GEN-LAST:event_btn_estrellaActionPerformed

    private void btn_regaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regaloActionPerformed
        emoji = "🎁";
        desarrolloJuego(emoji);
    }//GEN-LAST:event_btn_regaloActionPerformed
    
    private void desarrolloJuego(String emoji){
        String matriz [][] = new String [4][4];
        int encontrados = 0;
        Controlador controlador = new Controlador();
        
        if(!(tf_input.getText().equals("")) && (Integer.parseInt(tf_input.getText()) >= 0) && (Integer.parseInt(tf_input.getText()) <= 16)){
            matriz = controlador.cargarMatriz(matriz);
            encontrados = controlador.buscarEmoji(matriz, emoji);
            pintarResultados(matriz, emoji, encontrados);
            
        }
    }
    
    private void pintarResultados(String matriz[][], String emoji, int encontrados){
        String contenido = "";
        
        for(int i=0; i<4; i++){
            for(int j=0; j<4; j++){
                contenido += matriz[i][j] + " ";
            }
            contenido += "\n";
        }
        
        ta_matriz.setText(contenido);
        tf_elegido.setText(emoji);
        tf_cantidad.setText(tf_input.getText());
        tf_encontrados.setText(String.valueOf(encontrados));
        if(encontrados == Integer.parseInt(tf_input.getText())){
            tf_resultado.setText("HA ACERTADO");
        }else{
            tf_resultado.setText("HA FALLADO");
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_arbol;
    private javax.swing.JButton btn_estrella;
    private javax.swing.JButton btn_papanoel;
    private javax.swing.JButton btn_regalo;
    private javax.swing.JButton btn_reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta_matriz;
    private javax.swing.JTextField tf_cantidad;
    private javax.swing.JTextField tf_elegido;
    private javax.swing.JTextField tf_encontrados;
    private javax.swing.JTextField tf_input;
    private javax.swing.JTextField tf_resultado;
    // End of variables declaration//GEN-END:variables
}
